[deps]
Arblib = "fb37089c-8514-4489-9461-98f9c8763369"
CAPCourseS26 = "325d8c3c-64d7-4eca-a09e-82c33fcfa9bb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
